### ISSUE TITLE
FEATURE REQUEST: Automatic import of community packages, if no local one found

### ISSUE THREAD

**Issue by unquietwiki** [chocolatey/simple-server#47] opened 2018-06-01 02:11 UTC
I might be able to make this happen with some effort. Trying to get my own workplace using Chocolatey, and being able to cache some of the known-good external packages would be nice. Having to mess with a Squid / whatever instance for caching content seems excessive: the idea I have is that a failed package request could cache the community package; but still be over-writable by a local push.

Something like this might be useful, regardless of environment, or licensing status; since it'd be a potential bandwidth saver for any system involved. @ferventcoder any thoughts?

**Comment by ferventcoder** [comment] 2018-06-04 23:56
Howdy @unquietwiki - this is actually a duplicate of #16.

**Comment by ferventcoder** [comment] 2018-06-04 23:57
Duplicate of #16

**Comment by ferventcoder** [comment] 2018-06-04 23:58
There we go, now it's marked as a dupe. 

Comment/subscribe over there. Thanks!

**Closed by ferventcoder** 2018-06-04 23:58 UTC
Labels: duplicate

**Comment by unquietwiki** [comment] 2018-06-05 17:26
@ferventcoder Thank you! 👍
